spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_seata
    username: root
    password: 55555555
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true