spring:
  datasource:
    url: jdbc:mysql://host:3306/test_seata
    username: root
    password: password
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true